spring:
  application:
    name: simulacred
  devtools:
    livereload:
      enabled: true

springdoc:
  swagger-ui:
    path: /api-doc
  api-docs:
    path: /api-docs
    enabled: true
  enable-native-support: true

logging:
  level:
    root: "info"
    org.springframework.web: "info"